apiVersion: v1
kind: Service
metadata:
  name: kuma-tcp-echo-2
  namespace: kuma-app
spec:
  selector:
    app: kuma-tcp-echo-2
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuma-tcp-echo-2
  namespace: kuma-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuma-tcp-echo-2
  template:
    metadata:
      labels:
        app: kuma-tcp-echo-2
      annotations:
        kuma.io/mesh: default
    spec:
      containers:
      - name: kuma-tcp-echo
        image: kong-docker-kuma-docker.bintray.io/kuma-tcp-echo:0.1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
